# Generated by Django 3.0 on 2020-01-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('occupants', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
