# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_auto_20200120_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_picture',
            field=models.ImageField(default='default.jpg', upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
