# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20200120_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
