# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0008_auto_20200120_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
