# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0009_neighbourhood_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
